const MATOMO_URL = process.env.EXPO_PUBLIC_MATOMO_URL;
const MATOMO_IDSITE_1 = process.env.EXPO_PUBLIC_MATOMO_IDSITE_1;
const MATOMO_URL_2 = process.env.EXPO_PUBLIC_MATOMO_URL_2;
const MATOMO_IDSITE_2 = process.env.EXPO_PUBLIC_MATOMO_IDSITE_2;
const SCHEME = process.env.EXPO_PUBLIC_SCHEME;
const API_HOST = process.env.EXPO_PUBLIC_API_HOST;
const APP_ENV = process.env.EXPO_PUBLIC_APP_ENV;

export { MATOMO_URL, MATOMO_IDSITE_1, MATOMO_URL_2, MATOMO_IDSITE_2, SCHEME, API_HOST, APP_ENV };
