require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'oz_ensemble' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'oz_ensembleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.98.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'oz_ensemble-tvOS' do
  # Pods for oz_ensemble-tvOS

  target 'oz_ensemble-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
