jobs:
  runs:
    db:
      use: SocialGouv/kube-workflow/jobs/create-db
      with:
        pgAdminSecretRefName: azure-pg-admin-user
app:
  envFrom:
    - secretRef:
        name: pg-user-{{ .Values.global.branchSlug }}
