import envConfig from 'react-native-config';

const MATOMO_URL = envConfig.MATOMO_URL;
const MATOMO_IDSITE_1 = envConfig.MATOMO_IDSITE_1;
const MATOMO_URL_2 = envConfig.MATOMO_URL_2;
const MATOMO_IDSITE_2 = envConfig.MATOMO_IDSITE_2;
const SENTRY_XXX = envConfig.SENTRY_XXX;
const OPEN_FOOD_FACT_PASSWORD = envConfig.OPEN_FOOD_FACT_PASSWORD;
const OPEN_FOOD_FACT_USER_ID = envConfig.OPEN_FOOD_FACT_USER_ID;
const SCHEME = envConfig.SCHEME;
const API_HOST = envConfig.API_HOST;

export {
  MATOMO_URL,
  MATOMO_IDSITE_1,
  MATOMO_URL_2,
  MATOMO_IDSITE_2,
  SENTRY_XXX,
  OPEN_FOOD_FACT_PASSWORD,
  OPEN_FOOD_FACT_USER_ID,
  SCHEME,
  API_HOST,
};
