/* eslint-disable quotes */
export default {
  // key storage
  STORE_KEY_ONBOARDING_DONE: '@OnboardingDoneWithCGU',
  STORE_KEY_QUIZZ_ANSWERS: '@Quizz_answers',
  STORE_KEY_QUIZZ_RESULT: '@Quizz_result',
  STORE_KEY_CHALLENGE7DAYS_QUIZZ_J2_ANSWERS: '@Challenge7d_Quizz_j2_answers',
  STORE_KEY_CHALLENGE7DAYS_QUIZZ_J2_RESULT: '@Challenge7d_Quizz_j2_result',
  STORE_KEY_CHALLENGE7DAYS_QUIZZ_J4_ANSWERS: '@Challenge7d_Quizz_j4_answers',
  STORE_KEY_CHALLENGE7DAYS_QUIZZ_J4_RESULT: '@Challenge7d_Quizz_j4_result',
  STORE_KEY_CHALLENGE7DAYS_QUIZZ_J6_ANSWERS: '@Challenge7d_Quizz_j6_answers',
  STORE_KEY_CHALLENGE7DAYS_QUIZZ_J6_RESULT: '@Challenge7d_Quizz_j6_result',
  STORE_KEY_REMINDER: '@Reminder',
  STORE_KEY_ASKED_FOR_NOTIFICATIONS_IOS: '@Reminder',
  STORE_KEY_NUMBER_OF_VISITS: '@NumberOfVisits',
  STORE_KEY_USER_ID: '@UserIdv2',
  STORE_KEY_DONT_SHOW_SCAN_ALERT: '@ScanAlert',
  //  notifs
  NOTIF_REMINDER_TITLE: "C'est l'heure de votre suivi quotidien !",
  NOTIF_REMINDER_MESSAGE: "N'oubliez pas de remplir votre agenda Oz",
  // views
  VIEW_WELCOME: 'WELCOME',
  VIEW_QUIZZ: 'QUIZZ',
  VIEW_CONTACT: 'CONTACT',
  VIEW_CONSO: 'CONSO',
  VIEW_REMINDER: 'REMINDER',
  VIEW_EXPORT: 'EXPORT',
  VIEW_CGU: 'CGUS',
  VIEW_PRIVACY_POLICY: 'POLICY',
  VIEW_INFOS: 'INFOS',
  VIEW_LEGALS: 'LEGALS',
  // from
  FROM_MENU: 1,
  FROM_INIT_ROUTE: 2,
  FROM_LOCAL_NOTIFICATION: 3,
  FROM_BACKGROUND_NOTIFICATION: 4,
  FROM_WELCOME: 5,
  FROM_QUIZZ: 6,
  FROM_CONTACT: 7,
  FROM_CONSO: 8,
  FROM_REMINDER: 9,
  FROM_RESULT: 10,
  // questions
  SCORE: 'score',
  GENDER: 'gender',
  MAN: 'man',
  WOMAN: 'woman',
  FREQUENCY: 'frequency',
  NEVER: 'never',
  ONCE_A_MONTH: 'once-a-month',
  TWICE_A_MONTH: 'twice-a-month',
  TWICE_A_WEEK: 'twice-a-week',
  FOUR_TIMES_A_WEEK: 'four-times-a-week',
  GLASSES: 'glasses',
  LESS_THAN_THREE: 'less-than-three',
  THREE: 'three',
  FIVE: 'five',
  SEVEN: 'seven',
  TEN: 'ten',
  BINGE: 'binge',
  LESS_THAN_ONCE_A_MONTH: 'less-than-once-a-month',
  MORE_THAN_ONCE_A_MONTH: 'more-than-once-a-month',
  ONCE_A_WEEK: 'once-a-week',
  EVERYDAY: 'everyday',
  NO: 'no',
  YES_BUT_NOT_LAST_YEAR: 'yes-but-not-last-year',
  YES_LAST_YEAR: 'yes-last-year',
  // life quality
  NOT_AT_ALL: 'not-at-all',
  SLIGHTLY: 'slightly',
  MODERATELY: 'moderately',
  A_LOT: 'a-lot',
  VERY_MUCH: 'very-much',

  NONE: 'none',
  VERY_LOW: 'very-low',
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  VERY_HIGH: 'very-high',

  // results
  RESULT_ADDICTED: 'addicted',
  RESULT_RISK: 'risk',
  RESULT_GOOD: 'good',
  ACTION_RESULTATS: 'action-resultats',
  ACTION_CONSOMMATION: 'action-consommation',
  ACTION_CONSEILLER: 'action-conseiller',
  ACTION_CONTACT: 'action-contact',
  ACTION_QUESTIONS: 'action-questions',
};
