projectName: ozensemble
ciNamespace: ci-ozensemble

dependencies:
  fabrique:
    extends:
      - name: ovh
        ifEnv: [dev, preprod]
      - name: buildkit-service
        ifEnv: [dev, preprod]
