app:
  containerPort: 3000
  probesPath: /healthz
  envFrom:
    - secretRef:
        name: "pg-user"
    - secretRef:
        name: api

jobs:
  runs:
    build-app:
      with:
        context: api
