# yaml-language-server: $schema=../../kontinuous/docs/values.schema.json

app:
  ~needs: [build-app, pg]
  containerPort: 3000
  probesPath: /healthz
  envFrom:
    - secretRef:
        name: "pg-app"
    - secretRef:
        name: api

pg:
  ~chart: pg

jobs:
  runs:
    build-app:
      with:
        context: api
