name: Preproduction

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: preproduction

jobs:
  register:
    name: Build & Register application
    runs-on: ubuntu-latest
    steps:
    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@v1
      with:
        environment: preprod
        token: ${{ secrets.GITHUB_TOKEN }}
        imagePackage: app
        dockercontext: ./api
        dockerfile: ./api/Dockerfile

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [register]
    environment:
      name: preproduction
      url: https://api-ozensemble-preprod.dev.fabrique.social.gouv.fr
    steps:
    - name: Use kube-workflow deployment
      uses: SocialGouv/kube-workflow@b1
      with:
        environment: preprod
        token: ${{ secrets.GITHUB_TOKEN }}
        kubeconfig: ${{ secrets.KUBECONFIG }}
        rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
        rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}
