export default {
  // from
  FROM_MENU: 1,
  FROM_INIT_ROUTE: 2,
  FROM_LOCAL_NOTIFICATION: 3,
  FROM_BACKGROUND_NOTIFICATION: 4,
  FROM_WELCOME: 5,
  FROM_QUIZZ: 6,
  FROM_CONTACT: 7,
  FROM_CONSO: 8,
  FROM_REMINDER: 9,
  FROM_RESULT: 10,

  // matomo custom dimensions
  MATOMO_CUSTOM_DIM_VERSION: 1,
  MATOMO_CUSTOM_DIM_SYSTEM: 2,
  MATOMO_CUSTOM_DIM_PROFILE: 3,
  MATOMO_CUSTOM_DIM_GENDER: 4,
  MATOMO_CUSTOM_DIM_AGE: 5,
};
